language: python

env:
  secure: "W/tCeyeLLrkWtavS+91FsdDll20geGIq/JSULgtr2wpJhqo20ZoyIOwWVlamqpzMvIVAs3wBbOuci3FVxgUJMKi+4eSAsHw4TOrkeNfxdzTKVeOgrZjHSvS/BC7t4ViQbzLjYqjO5rysl23Wt6hoc1YEFUGaF0aNL8RFz0j52+A="

python:
#  - "2.6" disabled
  - "2.7"
#  - "3.2"
#  - "3.3"
# command to install dependencies

git:
  submodules: false

branches:
  only:
    - master

before_install:
    # use utf8 encoding.  Should be default, but this is insurance against future changes
    - export PYTHONIOENCODING=UTF8

    - sudo apt-get update -qq
    - sudo apt-get install -qq python-sphinx
    - echo -e "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt

# command to run tests
script:
    - paver test
    - paver html
    - paver commit_doc