language: python

python:
#  - "2.6" disabled
  - "2.7"
#  - "3.2"
#  - "3.3"
# command to install dependencies

branches:
  only:
    - master

before_install:
    # use utf8 encoding.  Should be default, but this is insurance against future changes
    - export PYTHONIOENCODING=UTF8

    - sudo apt-get update -qq
    - sudo apt-get install -qq python-sphinx

install: "pip install -r requirements.txt"

# command to run tests
script: python test.py